### ISSUE TITLE
readme文件中Annotations和JPEGImages文件夹的解释是不是说反了？

### ISSUE THREAD

**Issue by baozidai** [CodingChaozhang/yolo3-keras-breath_mask#1]
├─Annotations  # 存放数据集中图片文件
├─JPEGImages   # 存放图片标签，xml 格式

是不是应该这样↓↓👇
Annotations 存xml
JPEGImages 存图

**Comment by CodingChaozhang** [comment]
对对，写错了



在 2020-02-17 18:43:29，"baozidai" <notifications@github.com> 写道：

├─Annotations # 存放数据集中图片文件
├─JPEGImages # 存放图片标签，xml 格式

是不是应该这样↓↓👇
Annotations 存xml
JPEGImages 存图
